# The base configuration file that defines the queues used by the document services 
# microservices
# 
#     Reserved Port Range: 5700 - 5750

rabbitmq:
            
  server:
    host: localhost
    port: 5672     

  document-dead-letter:                   # used in error handling for timeouts, failed retries, etc.
    input_queue: documents_input_DLQ      # dead messages reported by error handling services
    output_queue: documents_output_DLQ    

  ingestion:                          # initial file typing and validation
    input_queue: ingestion_input      # entry point for now so may not be required
    output_queue: ingestion_output    # report back of success (required?)
        
  preprocessing-docx:                 # Word files ready for pre-processing
    input_queue: preproc_docx_input   
    output_queue: preproc_docx_output
    